feat: added shp file to metadata conversion
MapColonies/discrete-agent pull request #11
Opened 2021-02-03 14:15 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                       |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

Closes #4 

Further  information:

2021-02-03 15:22 UTC, asafMasa requested changes
👍

2021-02-03 15:22 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +        return access(path, fsConstants.F_OK)
have you considered using https://www.npmjs.com/package/fs-extra?

2021-02-03 15:22 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +        if(await this.fileExists(filesShp) && await this.fileExists(filesDbf) &&
why not https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all?

2021-02-03 15:22 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +        const filesShp = `${directory}/Files.shp`;
Refactor this code to a higher level methods such as: 
validateMetadataFilesExists() => check for metadata files
const metaInJson = parseMetaData() => parse the metadata to JSON format
validateImageFilesExists() => check for images files

2021-02-03 15:22 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +}
end of file

2021-02-03 15:22 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +        await this.fileExists(metadataShp) && await this.fileExists(metadataDbf)) {
Raise proper error for missing files

2021-02-04 05:42 UTC, cl-shaharshavit-rnd commented on src/layerCreator/models/trigger.ts
> +        return access(path, fsConstants.F_OK)
is it worth adding additional dependency for that?

2021-02-04 05:44 UTC, cl-shaharshavit-rnd commented on src/layerCreator/models/trigger.ts
> +        if(await this.fileExists(filesShp) && await this.fileExists(filesDbf) &&
most of the times it is called files will be missing and I don't want to wait to check all of them if I don't have to

2021-02-04 05:46 UTC, cl-shaharshavit-rnd commented on src/layerCreator/models/trigger.ts
> +        await this.fileExists(metadataShp) && await this.fileExists(metadataDbf)) {
missing file is not an error.
it will usually meant the copy of files is still in progress

2021-02-04 08:48 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +        await this.fileExists(metadataShp) && await this.fileExists(metadataDbf)) {
Split manual trigger and watch error handling - if manually triggered throw an error for missing file

2021-02-04 09:10 UTC, asafMasa requested changes

2021-02-04 09:10 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +      this.parseToMetadata(productGeoJson, metaDataGeoJson, files);
const metadata = ...

2021-02-07 09:47 UTC, AnguIar approved these changes

2021-02-07 10:04 UTC, merged