refactor: migrate discrete-agent into ts-boilerplate
MapColonies/discrete-agent pull request #2
Opened 2022-07-11 14:04 UTC by ronenkapelian

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-07-12 08:39 UTC, asafMasa requested changes
Good Job👍

2022-07-12 08:39 UTC, asafMasa commented on .vscode/launch.json
> +    {
revert, run git command to ignore this in the future - [git update-index --assume-unchanged <file>](https://stackoverflow.com/questions/17195861/undo-git-update-index-assume-unchanged-file)

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "minTriggerDepth": "WATCH_MIN_TRIGGER_DEPTH",
add "__format": "number"

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "maxWatchDepth": "WATCH_MAX_TRIGGER_DEPTH",
add "__format": "number"

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "interval": "WATCH_INTERVAL"
add "__format": "number"

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "retries": "WATCHER_SHP_RETRY_COUNT",
add "__format": "number"

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "factor": "WATCHER_SHP_RETRY_FACTOR",
add "__format": "number"

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "minTimeout": "WATCHER_SHP_RETRY_MIN_TIMEOUT",
add "__format": "number"

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "maxTimeout": "WATCHER_SHP_RETRY_MAX_TIMEOUT",
add "__format": "number"

2022-07-12 08:39 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "randomize": "WATCHER_SHP_RETRY_RANDOMIZE"
add "__format": "boolean"

2022-07-12 08:39 UTC, asafMasa commented on helm/templates/configmap.yaml
> -  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
add this config param

2022-07-12 08:39 UTC, asafMasa commented on helm/templates/configmap.yaml
> -  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
add this config param

2022-07-12 08:39 UTC, asafMasa commented on helm/templates/configmap.yaml
> -  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
add this config param

2022-07-12 08:39 UTC, asafMasa commented on helm/values.yaml
> -  logPrettyPrintEnabled: false
return this value

2022-07-12 08:39 UTC, asafMasa commented on helm/values.yaml
> -  responseCompressionEnabled: true
return this value

2022-07-12 08:39 UTC, asafMasa commented on helm/values.yaml
> -  requestPayloadLimit: 1mb
return this value

2022-07-12 08:39 UTC, asafMasa commented on src/layerCreator/models/shpParser.ts
> +      // throw new BadRequestError(`Invalid shp file: ${shp}, err: ${error.message}`);
remove remark

2022-07-12 08:39 UTC, asafMasa commented on src/serviceClients/agentDbClient.ts
> +      return await this.put('/status', status);
add info log

2022-07-12 13:10 UTC, ronenkapelian commented on src/serviceClients/agentDbClient.ts
> +      return await this.put('/status', status);
done

2022-07-12 13:10 UTC, ronenkapelian commented on src/layerCreator/models/shpParser.ts
> +      // throw new BadRequestError(`Invalid shp file: ${shp}, err: ${error.message}`);
done

2022-07-12 13:10 UTC, ronenkapelian commented on helm/values.yaml
> -  requestPayloadLimit: 1mb
done

2022-07-12 13:10 UTC, ronenkapelian commented on helm/values.yaml
> -  responseCompressionEnabled: true
done

2022-07-12 13:10 UTC, ronenkapelian commented on helm/values.yaml
> -  logPrettyPrintEnabled: false
done

2022-07-12 13:10 UTC, ronenkapelian commented on config/custom-environment-variables.json
> +      "retries": "WATCHER_SHP_RETRY_COUNT",
done

2022-07-12 13:10 UTC, ronenkapelian commented on config/custom-environment-variables.json
> +      "interval": "WATCH_INTERVAL"
done

2022-07-12 13:10 UTC, ronenkapelian commented on config/custom-environment-variables.json
> +      "maxWatchDepth": "WATCH_MAX_TRIGGER_DEPTH",
done

2022-07-12 13:10 UTC, ronenkapelian commented on config/custom-environment-variables.json
> +      "minTriggerDepth": "WATCH_MIN_TRIGGER_DEPTH",
done

2022-07-12 13:10 UTC, ronenkapelian commented on .vscode/launch.json
> +    {
done

2022-07-13 06:55 UTC, asafMasa requested changes
You didn't resolve all of the previous comments

2022-07-13 06:55 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "__format": "number"
bug!

2022-07-13 07:01 UTC, ronenkapelian commented on config/custom-environment-variables.json
> +      "__format": "number"
done, fixed.

2022-07-13 07:17 UTC, ronenkapelian commented on helm/templates/configmap.yaml
> -  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
done

2022-07-13 07:17 UTC, ronenkapelian commented on helm/templates/configmap.yaml
> -  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
done

2022-07-13 07:17 UTC, ronenkapelian commented on helm/templates/configmap.yaml
> -  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
done

2022-07-13 08:32 UTC, asafMasa approved these changes

2022-07-13 08:35 UTC, merged