feat: models mapping
MapColonies/discrete-agent pull request #25
Opened 2021-03-03 15:30 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                       |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

Closes #21

2021-03-03 16:21 UTC, asafMasa requested changes
Great Job!

2021-03-03 16:21 UTC, asafMasa commented on src/layerCreator/models/metadataMapper.ts
> +import _ from 'lodash';
import { get } from ....

2021-03-03 16:21 UTC, asafMasa commented on src/layerCreator/models/trigger.ts
> +      const metadata = this.metadataMapper.map(productGeoJson, metaDataGeoJson, filesGeoJson);
try catch on the parsing (maping) section?

2021-03-03 16:21 UTC, asafMasa commented on tests/unit/layerCreator/models/metadataMapper.spec.ts
> +    it('metadata is map according to model', () => {
do you want to add test for incorrect mapping vs actual file?

2021-03-04 06:43 UTC, cl-shaharshavit-rnd commented on src/layerCreator/models/metadataMapper.ts
> +import _ from 'lodash';
changed

2021-03-04 06:45 UTC, cl-shaharshavit-rnd commented on src/layerCreator/models/trigger.ts
> +      const metadata = this.metadataMapper.map(productGeoJson, metaDataGeoJson, filesGeoJson);
this method cant throw any catchable error so there is no need for a catch

2021-03-04 06:48 UTC, cl-shaharshavit-rnd commented on tests/unit/layerCreator/models/metadataMapper.spec.ts
> +    it('metadata is map according to model', () => {
what do you mean?
the mapping cant be incorrect as its from the models.
the mapping also don't validate the models so missing data in the source will just result in empty values

2021-03-04 07:50 UTC, asafMasa approved these changes

2021-03-04 08:06 UTC, merged