Add helm
MapColonies/discrete-agent pull request #89
Opened 2022-03-10 12:26 UTC by AnguIar

2022-03-10 13:23 UTC, asafMasa requested changes

2022-03-10 13:23 UTC, asafMasa commented on helm/templates/deployment.yaml
> +            {{- if eq (upper .Values.env.classification.storageProvider) "FS" }}
i think there is a support for S3 - check with @cl-shaharshavit-rnd

2022-03-10 13:23 UTC, asafMasa commented on helm/templates/deployment.yaml
> +            - name: EXTERNAL_READINESS_URL
?

2022-03-10 13:23 UTC, asafMasa commented on helm/templates/deployment.yaml
> +              value: {{ printf "[%s/%s]" .Values.caPath .Values.caKey | quote }}
REQUESTS_CA_BUNDLE & NODE_EXTRA_CA_CERTS has the same value, is it valid? the only difference is "%s/%s" vs "[%s/%s]"

2022-03-10 13:28 UTC, asafMasa requested changes

2022-03-10 13:28 UTC, asafMasa commented on helm/Chart.yaml
> +version: 1.0.0
is this the service version?

2022-03-10 13:42 UTC, AnguIar commented on helm/templates/deployment.yaml
> +              value: {{ printf "[%s/%s]" .Values.caPath .Values.caKey | quote }}
REQUEST_CA_BUNDLE is a python env
NODE_EXTRA_CA_CERTS is a nodejs env
(it's a copy-paste by the way)

2022-03-10 13:42 UTC, AnguIar commented on helm/templates/deployment.yaml
> +            - name: EXTERNAL_READINESS_URL
It's a configuration in the service: https://github.com/MapColonies/discrete-agent/blob/master/config/custom-environment-variables.json

2022-03-10 13:42 UTC, AnguIar commented on helm/templates/deployment.yaml
> +            {{- if eq (upper .Values.env.classification.storageProvider) "FS" }}
There is an `else` clause

2022-03-10 13:43 UTC, AnguIar commented on helm/Chart.yaml
> +version: 1.0.0
it's the helm version of the service

2022-03-10 13:46 UTC, asafMasa requested changes

2022-03-10 13:46 UTC, asafMasa commented on helm/templates/deployment.yaml
> +            - name: EXTERNAL_READINESS_URL
so why the value is empty?

2022-03-13 06:00 UTC, cl-shaharshavit-rnd commented on helm/templates/deployment.yaml
> +            - name: EXTERNAL_READINESS_URL
I think it was meant for deploying the agent as sidecar for another service or maybe split it to http and watcher services.
either way its irrelevant for our current deployment (no value is for "stand alone" deployment)

2022-03-13 06:14 UTC, cl-shaharshavit-rnd approved these changes

2022-03-13 08:37 UTC, asafMasa approved these changes

2022-03-16 10:08 UTC, merged